### ISSUE TITLE
working?

### ISSUE THREAD

**Issue by Aub-C** [aditosoftware/docker-crushftp#1]
Does crushftp actually work in Docker? Are you currently using this?

**Comment by bdito** [comment]
Yes, I am currently using this image.
I just pushed a new commit for improved readme and other changes.
You also need multiple volume mounts for example the configuration file (/var/opt/CrushFTP8_PC/prefs.XML), the user accounts (/var/opt/CrushFTP8_PC/users/) and the Temp Accounts (/var/opt/CrushFTP8_PC/TempAccounts/).
